namespace StockSharp.Dnse;

/// <summary>
/// DNSE second-factor methods.
/// </summary>
[DataContract]
[Serializable]
public enum DnseOtpTypes
{
    /// <summary>Email OTP.</summary>
    [EnumMember]
    Email,

    /// <summary>Smart OTP generated by the DNSE application.</summary>
    [EnumMember]
    Smart,
}

/// <summary>
/// Native DNSE order types.
/// </summary>
[DataContract]
[Serializable]
public enum DnseOrderTypes
{
    /// <summary>Choose from the StockSharp order type and time in force.</summary>
    [EnumMember]
    Auto,

    /// <summary>Limit order (LO).</summary>
    [EnumMember]
    Limit,

    /// <summary>Market order, match or kill (MOK).</summary>
    [EnumMember]
    MatchOrKill,

    /// <summary>Market order, match and kill (MAK).</summary>
    [EnumMember]
    MatchAndKill,

    /// <summary>Market-to-limit order (MTL).</summary>
    [EnumMember]
    MarketToLimit,

    /// <summary>Opening auction order (ATO).</summary>
    [EnumMember]
    AtOpen,

    /// <summary>Closing auction order (ATC).</summary>
    [EnumMember]
    AtClose,

    /// <summary>Post-limit order (PLO).</summary>
    [EnumMember]
    PostLimit,
}
