<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common_connectors.props" />


  <ItemGroup>
    <None Update="Gateway\activ_gateway.cjs"
          CopyToOutputDirectory="PreserveNewest"
          TargetPath="ActivFinancialGateway\activ_gateway.cjs"
          Pack="true"
          PackagePath="gateway\activ_gateway.cjs" />
    <None Update="Gateway\package.json"
          CopyToOutputDirectory="PreserveNewest"
          TargetPath="ActivFinancialGateway\package.json"
          Pack="true"
          PackagePath="gateway\package.json" />
  </ItemGroup>
</Project>
