namespace StockSharp.SierraChartDtc;

/// <summary>DTC order parameters.</summary>
[Serializable]
[DataContract]
[Display(
	ResourceType = typeof(LocalizedStrings),
	Name = LocalizedStrings.SierraChartDtcKey)]
public class SierraChartDtcOrderCondition : OrderCondition, IStopLossOrderCondition
{
	/// <summary>Stop activation price.</summary>
	[DataMember]
	[Display(ResourceType = typeof(LocalizedStrings), Name = LocalizedStrings.StopPriceKey,
		Description = LocalizedStrings.StopPriceDescKey, GroupName = LocalizedStrings.ParametersKey, Order = 0)]
	public decimal? StopPrice
	{
		get => Parameters.TryGetValue(nameof(StopPrice))?.To<decimal?>();
		set => Parameters[nameof(StopPrice)] = value;
	}

	/// <summary>Maximum quantity displayed publicly by the server.</summary>
	[DataMember]
	public decimal? MaxShowVolume
	{
		get => Parameters.TryGetValue(nameof(MaxShowVolume))?.To<decimal?>();
		set => Parameters[nameof(MaxShowVolume)] = value;
	}

	/// <summary>Free-form text forwarded to the DTC server.</summary>
	[DataMember]
	public string FreeFormText
	{
		get => Parameters.TryGetValue(nameof(FreeFormText))?.ToString();
		set => Parameters[nameof(FreeFormText)] = value;
	}

	/// <summary>Whether this order was generated by an automated system.</summary>
	[DataMember]
	public bool IsAutomated
	{
		get => Parameters.TryGetValue(nameof(IsAutomated))?.To<bool>() == true;
		set => Parameters[nameof(IsAutomated)] = value;
	}

	/// <summary>Whether this is a parent order.</summary>
	[DataMember]
	public bool IsParent
	{
		get => Parameters.TryGetValue(nameof(IsParent))?.To<bool>() == true;
		set => Parameters[nameof(IsParent)] = value;
	}

	/// <summary>Whether the derivative order opens a position.</summary>
	[DataMember]
	public bool IsOpenPosition
	{
		get => Parameters.TryGetValue(nameof(IsOpenPosition))?.To<bool>() == true;
		set => Parameters[nameof(IsOpenPosition)] = value;
	}

	decimal? IStopLossOrderCondition.ClosePositionPrice { get; set; }

	decimal? IStopLossOrderCondition.ActivationPrice
	{
		get => StopPrice;
		set => StopPrice = value;
	}

	bool IStopLossOrderCondition.IsTrailing
	{
		get => false;
		set
		{
			if (value)
				throw new NotSupportedException("The DTC base protocol does not define trailing-stop orders.");
		}
	}
}
