namespace StockSharp.TraderMade;

/// <summary>
/// Message adapter for TraderMade REST and WebSocket v2 APIs.
/// </summary>
[MediaIcon(Media.MediaNames.tradermade)]
[Doc("topics/api/connectors/forex/tradermade.html")]
[Display(
	ResourceType = typeof(LocalizedStrings),
	Name = LocalizedStrings.TraderMadeKey,
	Description = LocalizedStrings.MarketDataConnectorKey,
	GroupName = LocalizedStrings.ForexKey)]
[MessageAdapterCategory(
	MessageAdapterCategories.FX |
	MessageAdapterCategories.History |
	MessageAdapterCategories.RealTime |
	MessageAdapterCategories.Paid |
	MessageAdapterCategories.Level1 |
	MessageAdapterCategories.MarketDepth |
	MessageAdapterCategories.Candles)]
public partial class TraderMadeMessageAdapter : MessageAdapter
{
	private static readonly Uri _defaultRestEndpoint =
		new("https://marketdata.tradermade.com/api/v1/");
	private static readonly Uri _defaultStreamingEndpoint =
		new("wss://stream.tradermade.com/feedAdv");

	/// <summary>TraderMade REST API key.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.ApiKeyKey,
		Description = LocalizedStrings.TraderMadeRestKeyDescKey,
		GroupName = LocalizedStrings.ConnectionKey,
		Order = 0)]
	[BasicSetting]
	public SecureString RestKey { get; set; }

	/// <summary>TraderMade streaming API key.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.KeyKey,
		Description = LocalizedStrings.TraderMadeStreamingKeyDescKey,
		GroupName = LocalizedStrings.ConnectionKey,
		Order = 1)]
	public SecureString StreamingKey { get; set; }

	/// <summary>TraderMade REST API v1 root endpoint.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.RestEndpointKey,
		Description = LocalizedStrings.TraderMadeRestEndpointDescKey,
		GroupName = LocalizedStrings.AddressesKey,
		Order = 0)]
	public Uri RestEndpoint { get; set; } = _defaultRestEndpoint;

	/// <summary>TraderMade WebSocket v2 endpoint.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.StreamingEndpointKey,
		Description = LocalizedStrings.TraderMadeStreamingEndpointDescKey,
		GroupName = LocalizedStrings.AddressesKey,
		Order = 1)]
	public Uri StreamingEndpoint { get; set; } =
		_defaultStreamingEndpoint;

	private TimeSpan _requestInterval =
		TimeSpan.FromMilliseconds(500);

	/// <summary>Minimum interval between REST calls.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.IntervalKey,
		Description = LocalizedStrings.IntervalKey,
		GroupName = LocalizedStrings.ConnectionKey,
		Order = 2)]
	public TimeSpan RequestInterval
	{
		get => _requestInterval;
		set => _requestInterval =
			value >= TimeSpan.Zero &&
			value <= TimeSpan.FromMinutes(1)
				? value
				: throw new ArgumentOutOfRangeException(nameof(value),
					value, "TraderMade request interval must be " +
						"between zero and one minute.");
	}

	/// <summary>Request TraderLadder market depth.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.EnableLadderKey,
		Description = LocalizedStrings.TraderMadeEnableLadderDescKey,
		GroupName = LocalizedStrings.MarketDataKey,
		Order = 0)]
	public bool EnableLadder { get; set; }

	/// <summary>Request weekend cryptocurrency candles.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.WeekendDataKey,
		Description = LocalizedStrings.TraderMadeWeekendDescKey,
		GroupName = LocalizedStrings.MarketDataKey,
		Order = 1)]
	public bool Weekend { get; set; }

	/// <summary>Quote currencies used for generated pairs.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.QuoteCurrenciesKey,
		Description = LocalizedStrings.TraderMadeQuoteCurrenciesDescKey,
		GroupName = LocalizedStrings.FiltersKey,
		Order = 0)]
	public string QuoteCurrencies { get; set; } =
		"USD,EUR,GBP,JPY,BTC";

	/// <summary>Optional explicit symbol list.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.SymbolsKey,
		Description = LocalizedStrings.TraderMadeSymbolsDescKey,
		GroupName = LocalizedStrings.FiltersKey,
		Order = 1)]
	public string Symbols { get; set; }

	private int _maximumSecurities = 10000;

	/// <summary>Maximum securities generated by a lookup.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.MaximumItemsKey,
		Description = LocalizedStrings.TraderMadeMaximumSecuritiesDescKey,
		GroupName = LocalizedStrings.LimitsKey,
		Order = 0)]
	public int MaximumSecurities
	{
		get => _maximumSecurities;
		set => _maximumSecurities = value is >= 1 and <= 100000
			? value
			: throw new ArgumentOutOfRangeException(nameof(value),
				value, "Maximum security count must be between 1 " +
					"and 100000.");
	}

	/// <inheritdoc />
	public override void Save(SettingsStorage storage)
	{
		base.Save(storage);
		storage
			.Set(nameof(RestKey), RestKey)
			.Set(nameof(StreamingKey), StreamingKey)
			.Set(nameof(RestEndpoint), RestEndpoint)
			.Set(nameof(StreamingEndpoint), StreamingEndpoint)
			.Set(nameof(RequestInterval), RequestInterval)
			.Set(nameof(EnableLadder), EnableLadder)
			.Set(nameof(Weekend), Weekend)
			.Set(nameof(QuoteCurrencies), QuoteCurrencies)
			.Set(nameof(Symbols), Symbols)
			.Set(nameof(MaximumSecurities), MaximumSecurities);
	}

	/// <inheritdoc />
	public override void Load(SettingsStorage storage)
	{
		base.Load(storage);
		RestKey = storage.GetValue<SecureString>(nameof(RestKey));
		StreamingKey = storage.GetValue<SecureString>(
			nameof(StreamingKey));
		RestEndpoint = storage.GetValue(nameof(RestEndpoint),
			_defaultRestEndpoint);
		StreamingEndpoint = storage.GetValue(
			nameof(StreamingEndpoint), _defaultStreamingEndpoint);
		RequestInterval = storage.GetValue(nameof(RequestInterval),
			TimeSpan.FromMilliseconds(500));
		EnableLadder = storage.GetValue(nameof(EnableLadder), false);
		Weekend = storage.GetValue(nameof(Weekend), false);
		QuoteCurrencies = storage.GetValue(nameof(QuoteCurrencies),
			"USD,EUR,GBP,JPY,BTC");
		Symbols = storage.GetValue<string>(nameof(Symbols));
		MaximumSecurities = storage.GetValue(
			nameof(MaximumSecurities), 10000);
	}
}
