namespace StockSharp.Tradejini;

/// <summary>
/// Tradejini individual-app two-factor authentication types.
/// </summary>
[DataContract]
[Serializable]
public enum TradejiniTwoFactorTypes
{
    /// <summary>
    /// One-time password delivered by SMS or email.
    /// </summary>
    [EnumMember]
    Otp,

    /// <summary>
    /// Time-based code generated by an authenticator application.
    /// </summary>
    [EnumMember]
    Totp,
}

/// <summary>
/// Tradejini order products.
/// </summary>
[DataContract]
[Serializable]
public enum TradejiniProducts
{
    /// <summary>
    /// Delivery product for equities.
    /// </summary>
    [EnumMember]
    Delivery,

    /// <summary>
    /// Intraday product for equities and derivatives.
    /// </summary>
    [EnumMember]
    Intraday,

    /// <summary>
    /// Carry-forward product for derivatives.
    /// </summary>
    [EnumMember]
    Normal,
}

/// <summary>
/// Tradejini order validity values.
/// </summary>
[DataContract]
[Serializable]
public enum TradejiniValidities
{
    /// <summary>
    /// Valid for the current trading day.
    /// </summary>
    [EnumMember]
    Day,

    /// <summary>
    /// Immediate-or-cancel.
    /// </summary>
    [EnumMember]
    Ioc,

    /// <summary>
    /// End-of-session validity used by BSE.
    /// </summary>
    [EnumMember]
    Eos,

    /// <summary>
    /// Good-till-cancelled.
    /// </summary>
    [EnumMember]
    Gtc,
}
