<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common_connectors.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="$(MsExtensionsVer)" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="$(MsExtensionsVer)" />
  </ItemGroup>
</Project>
