//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSharp.MoexLchi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSharp.MoexLchi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0106194545
        ///018854
        ///02121965
        ///03101201
        ///05guzel
        ///08081993K
        ///09021809
        ///100_kg_S
        ///11111OG
        ///123
        ///128stock
        ///13031951
        ///131510
        ///1349967805
        ///1365sfhk
        ///138959
        ///13БК201
        ///146889
        ///147990
        ///155555
        ///1566
        ///1645@rey
        ///169 SNZ
        ///170355
        ///1853
        ///19031972
        ///1968gv1968
        ///1969April_JL
        ///19811981SV
        ///1984kin
        ///1992
        ///1V3CxD
        ///20112205AL
        ///2310
        ///251abc
        ///276787Grand
        ///27727
        ///29051983
        ///29101929
        ///3046
        ///3083523
        ///31615
        ///32303
        ///32305
        ///33296
        ///3615301
        ///3912800265
        ///4028R
        ///40EW2
        ///40FB7
        ///40FT7
        ///41
        ///420745
        ///42step
        ///4444
        ///44ghr77kc
        ///45_region
        ///47135
        ///471D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lci_2012_names {
            get {
                return ResourceManager.GetString("lci_2012_names", resourceCulture);
            }
        }
    }
}
