namespace StockSharp.Samco;

/// <summary>The message adapter for Samco Trade API.</summary>
[MediaIcon(Media.MediaNames.samco)]
[Doc("topics/api/connectors/stock_market/samco.html")]
[Display(
	ResourceType = typeof(LocalizedStrings),
	Name = LocalizedStrings.SamcoKey,
	Description = LocalizedStrings.StockConnectorKey,
	GroupName = LocalizedStrings.IndiaKey)]
[MessageAdapterCategory(
	MessageAdapterCategories.Asia |
	MessageAdapterCategories.RealTime |
	MessageAdapterCategories.History |
	MessageAdapterCategories.Candles |
	MessageAdapterCategories.Transactions |
	MessageAdapterCategories.Level1 |
	MessageAdapterCategories.MarketDepth |
	MessageAdapterCategories.Stock |
	MessageAdapterCategories.Futures |
	MessageAdapterCategories.Options)]
[OrderCondition(typeof(SamcoOrderCondition))]
public partial class SamcoMessageAdapter : MessageAdapter
{
	private const string _defaultRestEndpoint =
		"https://tradeapi.samco.in";
	private const string _defaultInstrumentEndpoint =
		"https://developers.stocknote.com/doc/ScripMaster.csv";
	private const string _defaultStreamingEndpoint =
		"wss://stream.samco.in";

	/// <summary>Encrypted API key generated by Samco.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.ApiKeyKey,
		Description = LocalizedStrings.SamcoApiKeyDescKey,
		GroupName = LocalizedStrings.ConnectionKey,
		Order = 0)]
	[BasicSetting]
	public SecureString Key { get; set; }

	/// <summary>Encrypted API secret generated by Samco.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.ApiSecretKey,
		Description = LocalizedStrings.SamcoApiSecretDescKey,
		GroupName = LocalizedStrings.ConnectionKey,
		Order = 1)]
	public SecureString Secret { get; set; }

	/// <summary>Existing daily Samco session token.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.SessionTokenKey,
		Description = LocalizedStrings.SamcoSessionTokenDescKey,
		GroupName = LocalizedStrings.ConnectionKey,
		Order = 2)]
	public SecureString SessionToken { get; set; }

	/// <summary>Samco REST root endpoint.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.RestEndpointKey,
		Description = LocalizedStrings.RestEndpointKey,
		GroupName = LocalizedStrings.AddressesKey,
		Order = 0)]
	public string RestEndpoint { get; set; } =
		_defaultRestEndpoint;

	/// <summary>Samco instrument-master CSV endpoint.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.InstrumentEndpointKey,
		Description = LocalizedStrings.InstrumentEndpointKey,
		GroupName = LocalizedStrings.AddressesKey,
		Order = 1)]
	public string InstrumentEndpoint { get; set; } =
		_defaultInstrumentEndpoint;

	/// <summary>Samco WebSocket endpoint.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.StreamingEndpointKey,
		Description = LocalizedStrings.StreamingEndpointKey,
		GroupName = LocalizedStrings.AddressesKey,
		Order = 2)]
	public string StreamingEndpoint { get; set; } =
		_defaultStreamingEndpoint;

	/// <summary>Enable streaming market data.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.StreamingKey,
		Description = LocalizedStrings.StreamingKey,
		GroupName = LocalizedStrings.ConnectionKey,
		Order = 3)]
	public bool StreamingEnabled { get; set; } = true;

	private TimeSpan _pollingInterval = TimeSpan.FromSeconds(5);

	/// <summary>REST polling interval.</summary>
	[Display(
		ResourceType = typeof(LocalizedStrings),
		Name = LocalizedStrings.PollingIntervalKey,
		Description = LocalizedStrings.PollingIntervalKey,
		GroupName = LocalizedStrings.ConnectionKey,
		Order = 4)]
	public TimeSpan PollingInterval
	{
		get => _pollingInterval;
		set => _pollingInterval =
			value >= TimeSpan.FromSeconds(1) &&
			value <= TimeSpan.FromMinutes(5)
				? value
				: throw new ArgumentOutOfRangeException(nameof(value),
					value, "Samco polling interval must be between " +
						"one second and five minutes.");
	}

	/// <inheritdoc />
	public override void Save(SettingsStorage storage)
	{
		base.Save(storage);
		storage
			.Set(nameof(Key), Key)
			.Set(nameof(Secret), Secret)
			.Set(nameof(SessionToken), SessionToken)
			.Set(nameof(RestEndpoint), RestEndpoint)
			.Set(nameof(InstrumentEndpoint), InstrumentEndpoint)
			.Set(nameof(StreamingEndpoint), StreamingEndpoint)
			.Set(nameof(StreamingEnabled), StreamingEnabled)
			.Set(nameof(PollingInterval), PollingInterval);
	}

	/// <inheritdoc />
	public override void Load(SettingsStorage storage)
	{
		base.Load(storage);
		Key = storage.GetValue<SecureString>(nameof(Key));
		Secret = storage.GetValue<SecureString>(nameof(Secret));
		SessionToken = storage.GetValue<SecureString>(
			nameof(SessionToken));
		RestEndpoint = storage.GetValue(nameof(RestEndpoint),
			_defaultRestEndpoint);
		InstrumentEndpoint = storage.GetValue(
			nameof(InstrumentEndpoint), _defaultInstrumentEndpoint);
		StreamingEndpoint = storage.GetValue(
			nameof(StreamingEndpoint), _defaultStreamingEndpoint);
		StreamingEnabled = storage.GetValue(
			nameof(StreamingEnabled), true);
		PollingInterval = storage.GetValue(nameof(PollingInterval),
			TimeSpan.FromSeconds(5));
	}
}
