namespace StockSharp.Comdirect;

/// <summary>
/// comdirect TAN procedure.
/// </summary>
public enum ComdirectTanTypes
{
    /// <summary>
    /// Use the customer's preferred TAN procedure.
    /// </summary>
    Preferred,

    /// <summary>
    /// PhotoTAN image.
    /// </summary>
    PhotoTan,

    /// <summary>
    /// Mobile TAN sent by SMS.
    /// </summary>
    MobileTan,

    /// <summary>
    /// PhotoTAN push approval.
    /// </summary>
    PhotoTanPush,
}

/// <summary>
/// TAN challenge generated by comdirect.
/// </summary>
public sealed class ComdirectTanChallenge
{
    /// <summary>
    /// Challenge identifier.
    /// </summary>
    public string Id { get; init; }

    /// <summary>
    /// Native TAN procedure.
    /// </summary>
    public string Type { get; init; }

    /// <summary>
    /// Phone hint or Base64-encoded PhotoTAN PNG.
    /// </summary>
    public string Challenge { get; init; }

    /// <summary>
    /// TAN procedures enabled for the account.
    /// </summary>
    public string[] AvailableTypes { get; init; } = [];
}
