namespace StockSharp.Firstock;

/// <summary>
/// The message adapter for Firstock Developer API.
/// </summary>
[MediaIcon(Media.MediaNames.firstock)]
[Doc("topics/api/connectors/stock_market/firstock.html")]
[Display(
    ResourceType = typeof(LocalizedStrings),
    Name = LocalizedStrings.FirstockKey,
    Description = LocalizedStrings.StockConnectorKey,
    GroupName = LocalizedStrings.IndiaKey)]
[MessageAdapterCategory(
    MessageAdapterCategories.Asia |
    MessageAdapterCategories.Transactions |
    MessageAdapterCategories.RealTime |
    MessageAdapterCategories.History |
    MessageAdapterCategories.Candles |
    MessageAdapterCategories.Ticks |
    MessageAdapterCategories.Level1 |
    MessageAdapterCategories.MarketDepth |
    MessageAdapterCategories.Stock |
    MessageAdapterCategories.Futures |
    MessageAdapterCategories.Options)]
[OrderCondition(typeof(FirstockOrderCondition))]
public partial class FirstockMessageAdapter : MessageAdapter, ITokenAdapter
{
    private static readonly Uri _defaultAddress = new("https://api.firstock.in/V1/");
    private static readonly Uri _defaultSymbolsAddress = new("https://api.firstock.in/V1/symbols/");
    private static readonly Uri _defaultWebSocketAddress = new("wss://socket.firstock.in/V2/ws");

    /// <summary>
    /// Firstock user identifier.
    /// </summary>
    [Display(
        ResourceType = typeof(LocalizedStrings),
        Name = LocalizedStrings.UserIdKey,
        Description = LocalizedStrings.UserIdKey + LocalizedStrings.Dot,
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 0)]
    [BasicSetting]
    public string UserId { get; set; }

    /// <summary>
    /// Firstock account password. It is SHA-256 hashed before login.
    /// </summary>
    [Display(
        ResourceType = typeof(LocalizedStrings),
        Name = LocalizedStrings.PasswordKey,
        Description = LocalizedStrings.PasswordKey + LocalizedStrings.Dot,
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 1)]
    [BasicSetting]
    public SecureString Password { get; set; }

    /// <summary>
    /// Current one-time password generated by the user's authenticator.
    /// </summary>
    [Display(
        Name = "TOTP",
        Description = "Current Firstock one-time password used by the login endpoint.",
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 2)]
    [BasicSetting]
    public SecureString OneTimePassword { get; set; }

    /// <summary>
    /// Vendor code issued by Firstock.
    /// </summary>
    [Display(
        Name = "Vendor code",
        Description = "Firstock vendor code, such as CLIENT_API.",
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 3)]
    [BasicSetting]
    public string VendorCode { get; set; }

    /// <summary>
    /// API key issued through the Firstock developer portal.
    /// </summary>
    [Display(
        Name = "API key",
        Description = "API key issued through the Firstock developer portal.",
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 4)]
    [BasicSetting]
    public SecureString ApiKey { get; set; }

    /// <inheritdoc />
    [Display(
        ResourceType = typeof(LocalizedStrings),
        Name = LocalizedStrings.TokenKey,
        Description = LocalizedStrings.TokenKey + LocalizedStrings.Dot,
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 5)]
    [BasicSetting]
    public SecureString Token { get; set; }

    /// <summary>
    /// Portfolio name emitted by the connector.
    /// </summary>
    [Display(
        Name = "Portfolio name",
        Description = "Portfolio name. When empty, the account returned by Firstock or the user ID is used.",
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 6)]
    public string PortfolioName { get; set; }

    /// <summary>
    /// Default product used for new orders.
    /// </summary>
    [Display(
        Name = "Default product",
        Description = "Default Firstock delivery, margin, or intraday product.",
        GroupName = LocalizedStrings.OrderKey,
        Order = 7)]
    public FirstockProducts DefaultProduct { get; set; } = FirstockProducts.Delivery;

    /// <summary>
    /// Default market-protection percentage.
    /// </summary>
    [Display(
        Name = "Market protection",
        Description = "Default protection percentage required for market and stop-market orders.",
        GroupName = LocalizedStrings.OrderKey,
        Order = 8)]
    public decimal MarketProtection { get; set; } = 1m;

    /// <summary>
    /// Divisor applied to integer WebSocket prices, which Firstock publishes in paise.
    /// </summary>
    [Display(
        Name = "Streaming price divisor",
        Description = "Divisor applied to Firstock V2 WebSocket price fields.",
        GroupName = LocalizedStrings.MarketDataKey,
        Order = 9)]
    public decimal PriceDivisor { get; set; } = 100m;

    /// <summary>
    /// Maximum number of streaming reconnect attempts.
    /// </summary>
    [Display(
        Name = "Reconnect attempts",
        Description = "Maximum number of attempts to reconnect the Firstock WebSocket.",
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 10)]
    public int ReconnectAttempts { get; set; } = 10;

    /// <summary>
    /// REST API root address.
    /// </summary>
    [Display(
        Name = "REST address",
        Description = "Firstock REST API root address.",
        GroupName = LocalizedStrings.AddressesKey,
        Order = 11)]
    public Uri Address { get; set; } = _defaultAddress;

    /// <summary>
    /// Public security-master root address.
    /// </summary>
    [Display(
        Name = "Symbols address",
        Description = "Firstock public symbol-file root address.",
        GroupName = LocalizedStrings.AddressesKey,
        Order = 12)]
    public Uri SymbolsAddress { get; set; } = _defaultSymbolsAddress;

    /// <summary>
    /// V2 WebSocket address.
    /// </summary>
    [Display(
        Name = "WebSocket address",
        Description = "Firstock V2 WebSocket address.",
        GroupName = LocalizedStrings.AddressesKey,
        Order = 13)]
    public Uri WebSocketAddress { get; set; } = _defaultWebSocketAddress;

    /// <summary>
    /// Interval for account snapshot refreshes.
    /// </summary>
    [Display(
        ResourceType = typeof(LocalizedStrings),
        Name = LocalizedStrings.IntervalKey,
        Description = LocalizedStrings.IntervalKey + LocalizedStrings.Dot,
        GroupName = LocalizedStrings.ConnectionKey,
        Order = 14)]
    public TimeSpan PollingInterval { get; set; } = TimeSpan.FromSeconds(30);

    /// <inheritdoc />
    public override void Save(SettingsStorage storage)
    {
        base.Save(storage);
        storage
            .Set(nameof(UserId), UserId)
            .Set(nameof(Password), Password)
            .Set(nameof(OneTimePassword), OneTimePassword)
            .Set(nameof(VendorCode), VendorCode)
            .Set(nameof(ApiKey), ApiKey)
            .Set(nameof(Token), Token)
            .Set(nameof(PortfolioName), PortfolioName)
            .Set(nameof(DefaultProduct), DefaultProduct)
            .Set(nameof(MarketProtection), MarketProtection)
            .Set(nameof(PriceDivisor), PriceDivisor)
            .Set(nameof(ReconnectAttempts), ReconnectAttempts)
            .Set(nameof(Address), Address)
            .Set(nameof(SymbolsAddress), SymbolsAddress)
            .Set(nameof(WebSocketAddress), WebSocketAddress)
            .Set(nameof(PollingInterval), PollingInterval);
    }

    /// <inheritdoc />
    public override void Load(SettingsStorage storage)
    {
        base.Load(storage);
        UserId = storage.GetValue<string>(nameof(UserId));
        Password = storage.GetValue<SecureString>(nameof(Password));
        OneTimePassword = storage.GetValue<SecureString>(nameof(OneTimePassword));
        VendorCode = storage.GetValue<string>(nameof(VendorCode));
        ApiKey = storage.GetValue<SecureString>(nameof(ApiKey));
        Token = storage.GetValue<SecureString>(nameof(Token));
        PortfolioName = storage.GetValue<string>(nameof(PortfolioName));
        DefaultProduct = storage.GetValue(nameof(DefaultProduct), DefaultProduct);
        MarketProtection = storage.GetValue(nameof(MarketProtection), MarketProtection);
        PriceDivisor = storage.GetValue(nameof(PriceDivisor), PriceDivisor);
        ReconnectAttempts = storage.GetValue(nameof(ReconnectAttempts), ReconnectAttempts);
        Address = storage.GetValue(nameof(Address), Address);
        SymbolsAddress = storage.GetValue(nameof(SymbolsAddress), SymbolsAddress);
        WebSocketAddress = storage.GetValue(nameof(WebSocketAddress), WebSocketAddress);
        PollingInterval = storage.GetValue(nameof(PollingInterval), PollingInterval);
    }
}
