<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common_connectors.props" />

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS3001;CS3003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Update="NativeBridge\**\*" Pack="true" PackagePath="native-source\%(RecursiveDir)%(Filename)%(Extension)" />
    <None Include="runtimes\win-x64\native\*.dll" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="runtimes\win-x64\native" />
    <None Include="runtimes\linux-x64\native\*.so" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="runtimes\linux-x64\native" />
  </ItemGroup>
</Project>
